### ISSUE TITLE
Automatic publishing of Helidon CLI to SDKMAN

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon-build-tools#352]
[SDKMAN](https://sdkman.io/vendors) is a popular JDK and SDK version manager, it would be very convenient to be able install the Helidon CLI with it as most of competitors are available there.

Installing Helidon CLI would be like:
```bash
sdk install helidon
```

Instead of:
```bash
sudo curl -LJ -o /usr/local/bin/helidon \
https://github.com/oracle/helidon-build-tools/releases/latest/download/helidon-cli-linux-amd64 && \
sudo chmod +x /usr/local/bin/helidon
```

Also switching the versions:
```bash
sdk default helidon 2.1.2
```

**Comment by barchetta** [comment]
Tool that might help: https://jreleaser.org/

**Comment by romain-grecourt** [comment]
@tvallin we should resume work on this since we have a proper `helidon-cli.zip`.
We should finalize the work on the homebrew package as well.

The automation shouldn't be hooked in the release workflow as we want a manual trigger for the final release steps (E.g. publishing to Maven Central), however we should have a script to automate cli updates to SDKMAN and Homebrew.
