### ISSUE TITLE
Error when using archetype for `helidon-quickstart-mp`

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon-build-tools#763]
## Environment Details
* Helidon Version: 3.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Running the QuickStart MP archetype like this
```
cd helidon/examples/microprofile
mvn archetype:generate -DinteractiveMode=false   \
  -DarchetypeGroupId=io.helidon.archetypes  \
  -DarchetypeArtifactId=helidon-quickstart-mp   \
  -DarchetypeVersion=3.0.0-SNAPSHOT   \
  -DgroupId=io.helidon.examples -DartifactId=http-status-count-mp   -Dpackage=io.helidon.examples.mp.httpstatuscount
```

fails with this display:
```
Reactor Summary for Helidon Microprofile Examples 3.0.0-SNAPSHOT:
[INFO] 
[INFO] Helidon Microprofile Examples GraphQL .............. SKIPPED
[INFO] Helidon Microprofile Examples Implicit Hello World . SKIPPED
[INFO] Helidon Microprofile Examples Explicit Hello World . SKIPPED
[INFO] Helidon Microprofile Examples MP 1.1 Static Content  SKIPPED
[INFO] Helidon Microprofile Examples MP 1.1 Security ...... SKIPPED
[INFO] Helidon Microprofile Examples IDCS Security ........ SKIPPED
[INFO] Helidon Microprofile Examples Multipart ............ SKIPPED
[INFO] Helidon Microprofile Examples OIDC Security ........ SKIPPED
[INFO] Helidon Microprofile Example Basic OpenAPI ......... SKIPPED
[INFO] Helidon Microprofile Examples WebSocket ............ SKIPPED
[INFO] Microprofile Reactive Messaging with SSE ........... SKIPPED
[INFO] Helidon Microprofile Example CORS .................. SKIPPED
[INFO] Helidon Microprofile Examples TLS .................. SKIPPED
[INFO] Helidon Microprofile Examples Multiple Ports ....... SKIPPED
[INFO] Helidon Bean Validation Example .................... SKIPPED
[INFO] Helidon Microprofile Examples ...................... FAILURE [  2.271 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.660 s
[INFO] Finished at: 2022-07-22T09:56:50-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project helidon-examples-microprofile-project: java.io.EOFException: input contained no data -> [Help 1]
```

The new project directory is created but the generated `pom.xml` is empty (and not other files are generated):
```
find http-status-count-mp 
http-status-count-mp
http-status-count-mp/pom.xml

tjquinn@tjquinn-mac microprofile % cat http-status-count-mp/pom.xml 
tjquinn@tjquinn-mac microprofile %
```

The archetype plug-in does update the `pom.xml` in the current directory to refer to the new submodule:
```
tail pom.xml 
            
    <module>multiport</module>
            
    <module>bean-validation</module>
          
    <module>http-status-count-mp</module>
      
  </modules>
  
</project>
```

**Comment by wliusa** [comment]
I invoke the Helidon archetype in an newly created empty folder and still see the same error.

**Comment by romain-grecourt** [comment]
Why are you referring to 3.0.0-SNAPSHOT ? What command did you run ?

**Comment by wliusa** [comment]
Because I followed https://helidon.io/docs/v3/#/mp/guides/quickstart
Generate the Project
Generate the project sources using one (or both) of the Helidon Maven archetypes. The result is a simple project that shows the basics of configuring the WebServer and implementing basic routing rules.

Run the Maven archetype
mvn -U archetype:generate -DinteractiveMode=false
-DarchetypeGroupId=io.helidon.archetypes
-DarchetypeArtifactId=helidon-quickstart-mp
-DarchetypeVersion=3.0.0-SNAPSHOT
-DgroupId=io.helidon.examples
-DartifactId=helidon-quickstart-mp
-Dpackage=io.helidon.examples.quickstart.mp

Got error:
...
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [io.helidon.archetypes:helidon-quickstart-mp:2.0.0-RC1] found in catalog remote
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/maven-metadata.xml
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/helidon-quickstart-mp-3.0.0-SNAPSHOT.pom
[WARNING] The POM for io.helidon.archetypes:helidon-quickstart-mp:jar:3.0.0-SNAPSHOT is missing, no dependency information available
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/helidon-quickstart-mp-3.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.203 s
[INFO] Finished at: 2022-08-05T11:47:11-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (io.helidon.archetypes:helidon-quickstart-mp:3.0.0-SNAPSHOT) -> [Help 1]

**Comment by wliusa** [comment]
> Why are you referring to 3.0.0-SNAPSHOT ? What command did you run ?

Because I followed https://helidon.io/docs/v3/#/mp/guides/quickstart
Generate the Project
Generate the project sources using one (or both) of the Helidon Maven archetypes. The result is a simple project that shows the basics of configuring the WebServer and implementing basic routing rules.

Run the Maven archetype
mvn -U archetype:generate -DinteractiveMode=false
-DarchetypeGroupId=io.helidon.archetypes
-DarchetypeArtifactId=helidon-quickstart-mp
-DarchetypeVersion=3.0.0-SNAPSHOT
-DgroupId=io.helidon.examples
-DartifactId=helidon-quickstart-mp
-Dpackage=io.helidon.examples.quickstart.mp

Got error:
...
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [io.helidon.archetypes:helidon-quickstart-mp:2.0.0-RC1] found in catalog remote
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/maven-metadata.xml
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/helidon-quickstart-mp-3.0.0-SNAPSHOT.pom
[WARNING] The POM for io.helidon.archetypes:helidon-quickstart-mp:jar:3.0.0-SNAPSHOT is missing, no dependency information available
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/helidon-quickstart-mp-3.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.203 s
[INFO] Finished at: 2022-08-05T11:47:11-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (io.helidon.archetypes:helidon-quickstart-mp:3.0.0-SNAPSHOT) -> [Help 1]

**Comment by tvallin** [comment]
Work is already in progress: https://github.com/oracle/helidon/pull/4679 to update documentation.
You can run the following command from an empty directory: 
```
mvn -U archetype:generate -DinteractiveMode=false 
    -DarchetypeGroupId=io.helidon.archetypes
    -DarchetypeArtifactId=helidon-quickstart-mp 
    -DarchetypeVersion=3.0.0 
    -DgroupId=io.helidon.examples 
    -DartifactId=helidon-quickstart-mp 
    -Dpackage=io.helidon.examples.quickstart.mp
```

**Comment by wliusa** [comment]
> 

Thanks

**Comment by wliusa** [comment]
From https://helidon.io/docs/v3/#/mp/guides/tracing
Tracing at the Method Level
To trace at the method level, you just annotate a method with @Traced.

Update the GreetingProvider class; 1) Add a new import and 2) Add the @Traced annotation to the getMessage method:
import org.eclipse.microprofile.opentracing.Traced; 

class MyClass{
    @Traced  
    String getMessage() {
        return message.get();
    }
}
Cannot find @Traced and its import

mvn package -DskipTests=true
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] Unrecognised tag: 'server' (position: START_TAG seen ...  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n\n<server>... @6:9)  @ /Users/weiweli/.m2/settings.xml, line 6, column 9
[WARNING] 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.15
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 15
[INFO] os.detected.classifier: osx-x86_64
[INFO] 
[INFO] -------------< io.helidon.examples:helidon-quickstart-mp >--------------
[INFO] Building helidon-quickstart-mp 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ helidon-quickstart-mp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ helidon-quickstart-mp ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /Users/weiweli/src/helidon/v3/helidon-quickstart-mp/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/weiweli/src/helidon/v3/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetingProvider.java:[10,44] package org.eclipse.microprofile.opentracing does not exist
[ERROR] /Users/weiweli/src/helidon/v3/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetingProvider.java:[29,6] cannot find symbol
  symbol:   class Traced
  location: class io.helidon.examples.quickstart.mp.GreetingProvider
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.348 s
[INFO] Finished at: 2022-08-08T13:54:46-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project helidon-quickstart-mp: Compilation failure: Compilation failure: 
[ERROR] /Users/weiweli/src/helidon/v3/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetingProvider.java:[10,44] package org.eclipse.microprofile.opentracing does not exist
[ERROR] /Users/weiweli/src/helidon/v3/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetingProvider.java:[29,6] cannot find symbol
[ERROR]   symbol:   class Traced
[ERROR]   location: class io.helidon.examples.quickstart.mp.GreetingProvider
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Traced** [comment]
您好，我看到以后就回复您

**Comment by wliusa** [comment]
Here is the file

package io.helidon.examples.quickstart.mp;

import java.util.concurrent.atomic.AtomicReference;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.eclipse.microprofile.opentracing.Traced;
/**
 * Provider for greeting message.
 */
@ApplicationScoped
public class GreetingProvider {
    private final AtomicReference<String> message = new AtomicReference<>();

    /**
     * Create a new greeting provider, reading the message from configuration.
     *
     * @param message greeting to use
     */
    @Inject
    public GreetingProvider(@ConfigProperty(name = "app.greeting") String message) {
        this.message.set(message);
    }

    // To enable tracing on getMessage (and other CDI beans), use @Traced annotation
    @Traced
    String getMessage() {
        return message.get();
    }

    void setMessage(String message) {
        this.message.set(message);
    }
}

**Comment by wliusa** [comment]
mvn -v      
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven-3.8.6
Java version: 18.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-18.0.2.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Comment by wliusa** [comment]
Pom file:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.helidon.applications</groupId>
        <artifactId>helidon-mp</artifactId>
        <version>3.0.0</version>
        <relativePath/>
    </parent>
    <groupId>io.helidon.examples</groupId>
    <artifactId>helidon-quickstart-mp</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.helidon.microprofile.bundles</groupId>
            <artifactId>helidon-microprofile-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.openapi</groupId>
            <artifactId>helidon-microprofile-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.microprofile.metrics</groupId>
            <artifactId>microprofile-metrics-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.metrics</groupId>
            <artifactId>helidon-microprofile-metrics</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.health</groupId>
            <artifactId>helidon-microprofile-health</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.tests</groupId>
            <artifactId>helidon-microprofile-tests-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.tracing</groupId>
            <artifactId>helidon-tracing-zipkin</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-libs</id>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.helidon.build-tools</groupId>
                <artifactId>helidon-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>third-party-license-report</id>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jboss.jandex</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>make-index</id>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by barchetta** [comment]
@wliusa I have created issues for the problems you are running into. These are documentation issues:

* https://github.com/oracle/helidon/issues/4685
* https://github.com/oracle/helidon/issues/4686

In the future please use Slack ([#helidon-users](http://slack.helidon.io/)) or Stack Overflow ([helidon tag](https://stackoverflow.com/tags/helidon)) for discussions. Or create a new GitHub issue instead of commenting on an existing one that is concerned with a different issue. I am removing your comments from this issue. If you have follow-up comments please use the issues I created above.

**Comment by wliusa** [comment]
> 

Thanks
