### ISSUE TITLE
About 3.0.7 release

### ISSUE THREAD

**Issue by chenrui333** [helidon-io/helidon-build-tools#991]
👋 it looks like 3.0.7 release did not get marked as latest release, raise this issue for some awareness. Thanks!

**Comment by chenrui333** [comment]
actually it also failed to build as well

see details in https://github.com/Homebrew/homebrew-core/pull/150582#issuecomment-1758377462

**Comment by romain-grecourt** [comment]
The bits were staged at oss.sonatype.org but never released. I'll re-spin and let you know when they are available so that you can retry the actions in your pull request.

**Comment by romain-grecourt** [comment]
@chenrui333 The bits for 3.0.7 are now available in Maven Central, you can retry the actions in your PR.

**Comment by chenrui333** [comment]
cool, thanks @romain-grecourt!

**Comment by chenrui333** [comment]
meanwhile, can you mark 3.0.7 as the latest release? Thanks!

![image](https://github.com/helidon-io/helidon-build-tools/assets/1580956/6725f6b4-7f49-4cfc-b604-995c78fcfecb)

**Comment by romain-grecourt** [comment]
This repository is a little peculiar as it is a mono repo (sort-of).
Every tag has a corresponding Maven release with artifacts deployed on Maven Central.

However, our cli is not distributed via Maven, we distribute it with GitHub release attachments. There are cases where we need to create a Maven release even though the cli wasn't updated, in this case we do not release the cli.

The trade-off is that we have gaps in the versions we use for the cli, however we don't release cli without updates.

---

It seems that you have some automation going-on that automates the pull requests in Homebrew ; can you describes how that works ?

Can it work with our current model, or do we need to update it so that the Homebrew automation works ?
E.g. 
- We could start releasing the cli for every tag
- We could move the cli to a dedicated repository (that could take some time)

**Comment by chenrui333** [comment]
> However, our cli is not distributed via Maven, we distribute it with GitHub release attachments. There are cases where we need to create a Maven release even though the cli wasn't updated, in this case we do not release the cli.

There are two solutions on this:
- release artifacts in sync, because it is generally a good thing, without too much thinking for bug reporting,
- or create separate tags like `cli/xxx` for cli releases



> It seems that you have some automation going-on that automates the pull requests in Homebrew ; can you describe how that works ?

either maintainer/contributor bump the formulae to the latest using livecheck, or you can integrate `https://github.com/mislav/bump-homebrew-formula-action` to help out the CLI releases, either way works for us.

**Comment by romain-grecourt** [comment]
Thanks for the suggestions. We will definitely look at using the GitHub action and creating cli specific tags.
